# Generated by Django 2.2.1 on 2019-05-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('pseudo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('dbirthDate', models.DateField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMsg', models.IntegerField()),
                ('textMessage', models.TextField()),
                ('etiquette', models.CharField(choices=[('BON', 'BON'), ('FAKE_NEWS', 'FNM'), ('HAINE', (('TRIBALISTE', 'TRIBALISTE'), ('ANTISEMIQUE', 'ANTISEMIQUE'), ('ISLAMOPHOBE', 'ISLAMOPHOBE')))], max_length=10)),
                ('dateAdded', models.DateField()),
                ('userSendMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User')),
            ],
        ),
    ]
