# Generated by Django 2.2.1 on 2019-06-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190524_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='userSendMessage',
            new_name='idUser',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='textMessage',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dbirthDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
